### ISSUE TITLE
Error creating directory on initial launch?

### ISSUE THREAD

**Issue by jehb** [superpowers/superpowers#23]
Just ran into this problem on Fedora/CentOS. Workaround is to create the directory manually. Something wrong with the mkdir code not creating the directory if it doesn't already exist?

Using data from /root/.local/share/Superpowers.
/root/superpowers-0.18.1-linux-x64/resources/app/server/paths.js:47
        throw err;
        ^

Error: ENOENT: no such file or directory, mkdir '/root/.local/share/Superpowers'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Object.<anonymous> (/root/superpowers-0.18.1-linux-x64/resources/app/server/paths.js:43:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/root/superpowers-0.18.1-linux-x64/resources/app/server/index.js:8:13)

**Comment by jehb** [comment]
(Just found duplicate issue)
